---
- name: Set up a fresh Debian workstation
  hosts: all

  # Edit these according to taste
  vars:
    usernam: changeme

  gather_facts: true
  force_handlers: true
  tasks:
    - name: Install needed packages
      ansible.builtin.include_tasks: "10-install-packages.yml"
    - name: Create main user
      ansible.builtin.include_tasks: "20-create-user.yml"
    - name: Copy custom configuration files
      ansible.builtin.include_tasks: "30-copy-configs.yml"
    - name: Fetch git repositories
      ansible.builtin.include_tasks: "40-git-some-more.yml"
    - name: Vim setup tasks
      ansible.builtin.include_tasks: "50-setup-vim.yml"
    - name: System-wide tweaks
      ansible.builtin.include_tasks: "60-system-tweaks.yml"

  handlers:
    - name: Restart nftables
      ansible.builtin.systemd:
        name: nftables
        state: restarted
        enabled: true
