- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: 'https://github.com/tyybbi/dotfiles.git'
    dest: "/tmp/dotfiles"
    version: master

- name: Clone scripts repo
  ansible.builtin.git:
    repo: 'https://github.com/tyybbi/scripts.git'
    dest: "/tmp/scripts"
    version: master

- name: Copy .vimrc
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/dotfiles/vimrc"
    dest: "/home/{{ usernam }}/.vimrc"
    owner: "{{ usernam }}"
    group: "{{ usernam }}"
    mode: '0640'

- name: Make vim plugin directories
  ansible.builtin.file:
    path: "/home/{{ usernam }}/.vim/pack/plugins/start"
    state: directory
    owner: "{{ usernam }}"
    group: "{{ usernam }}"
    mode: '0750'

- name: Create ~/bin (for update-vim-plugins to reside)
  ansible.builtin.file:
    path: "/home/{{ usernam }}/bin"
    state: directory
    owner: "{{ usernam }}"
    group: "{{ usernam }}"
    mode: '0750'

- name: Copy update-vim-plugins
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/scripts/update-vim-plugins"
    dest: "/home/{{ usernam }}/bin/update-vim-plugins"
    owner: "{{ usernam }}"
    group: "{{ usernam }}"
    mode: '0750'

- name: Clone vim-surround
  ansible.builtin.git:
    repo: 'https://github.com/tpope/vim-surround.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-surround"
    version: master

- name: Clone vim-fugitive
  ansible.builtin.git:
    repo: 'https://github.com/tpope/vim-fugitive.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-fugitive"
    version: master

- name: Clone vim-vinegar
  ansible.builtin.git:
    repo: 'https://github.com/tpope/vim-vinegar.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-vinegar"
    version: master

- name: Clone vim-speeddating
  ansible.builtin.git:
    repo: 'https://github.com/tpope/vim-speeddating.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-speeddating"
    version: master

- name: Clone taglist
  ansible.builtin.git:
    repo: 'https://github.com/vim-scripts/taglist.vim.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/taglist"
    version: master

- name: Clone splitjoin
  ansible.builtin.git:
    repo: 'https://github.com/AndrewRadev/splitjoin.vim.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/splitjoin"
    version: master

- name: Clone bufexplorer
  ansible.builtin.git:
    repo: 'https://github.com/jlanzarotta/bufexplorer.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/bufexplorer"
    version: master

- name: Clone vim-airline
  ansible.builtin.git:
    repo: 'https://github.com/vim-airline/vim-airline.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-airline"
    version: master

- name: Clone vim-easymotion
  ansible.builtin.git:
    repo: 'https://github.com/easymotion/vim-easymotion.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-easymotion"
    version: master

- name: Clone syntastic
  ansible.builtin.git:
    repo: 'https://github.com/vim-syntastic/syntastic.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/syntastic"
    version: master

- name: Clone vim-solarized8
  ansible.builtin.git:
    repo: 'https://github.com/lifepillar/vim-solarized8.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-solarized8"
    version: master

- name: Clone ctrlp
  ansible.builtin.git:
    repo: 'https://github.com/ctrlpvim/ctrlp.vim.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/ctrlp"
    version: master

- name: Clone ansible-doc
  ansible.builtin.git:
    repo: 'https://github.com/takelley1/ansible-doc.vim.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/ansible-doc.vim"
    version: main

- name: Clone ansible-vim
  ansible.builtin.git:
    repo: 'https://github.com/pearofducks/ansible-vim.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/ansible-vim"
    version: master

# - name: Clone coc.nvim
#   ansible.builtin.git:
#     repo: 'https://github.com/neoclide/coc.nvim.git'
#     dest: "/home/{{ usernam }}/.vim/pack/plugins/start/coc.nvim"
#     version: master

- name: Clone vim-commentary
  ansible.builtin.git:
    repo: 'https://github.com/tpope/vim-commentary.git'
    dest: "/home/{{ usernam }}/.vim/pack/plugins/start/vim-commentary"
    version: master

- name: Change permissions
  ansible.builtin.file:
    owner: "{{ usernam }}"
    group: "{{ usernam }}"
    path: "/home/{{ usernam }}/.vim"
    recurse: true
